### ISSUE TITLE
PackageUtilities.addImmutablePropertyFunction is not a function

### ISSUE THREAD

**Issue by iwoj** [convexset/meteor-log#1]
I get this error when trying to install your log package for the first time.

```
TypeError: PackageUtilities.addImmutablePropertyFunction is not a function
    at packages/convexset:log/log.js:230:20
```

**Comment by convexset** [comment]
That's unusual, what do you see when you `require('package-utils')` from the meteor shell?

**Comment by iwoj** [comment]
I can't get to the shell because this error is preventing meteor server from booting.

I installed package-utils with `meteor npm install --save package-utils` so it should be available.

**Comment by convexset** [comment]
Remove the log package first and see if `package-utils` appears as it should.

**Comment by iwoj** [comment]
Looks like it can't find `package-utils`. I get:

`Compiling undefined with meteor-babel without a cache`

and then:

`Error: Cannot find module 'package-utils'`

**Comment by convexset** [comment]
Try installing again and check `node_modules`. I just tried adding the package to a Meteor 1.7 app. It works fine.

**Comment by iwoj** [comment]
`ls -l node_modules/package-utils/` works. It's installed.

This is a pretty old meteor app that I've been continually updating. It's running with release `1.7.0.3` right now, but doesn't use ES6 features. Would that make a difference?

**Comment by convexset** [comment]
Hmmm... It works with the 1.7.0.3 app that I just installed it with. I'm rather perplexed about you can't even `require` the npm package.

**Comment by iwoj** [comment]
I've reproduced the error in a new app:


```
meteor create test
cd test
meteor npm install --save package-utils
meteor &
meteor shell
> require("package-utils")
```


results in

```
W20180812-10:42:39.216(-7)? (STDERR) Compiling undefined with meteor-babel without a cache
W20180812-10:42:39.280(-7)? (STDERR) [object Object]
W20180812-10:42:39.281(-7)? (STDERR)     at Object.exports.compile (/home/ubuntu/.meteor/packages/babel-compiler/.7.1.1.1ddn27j.rjz3++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-babel/index.js:77:13)
W20180812-10:42:39.281(-7)? (STDERR)     at Object.compile (packages/babel-compiler.js:44:29)
W20180812-10:42:39.281(-7)? (STDERR)     at Object.compileForShell (packages/ecmascript/ecmascript.js:7:18)
W20180812-10:42:39.282(-7)? (STDERR)     at REPLServer.wrappedDefaultEval [as eval] (packages/shell-server/shell-server.js:236:48)
W20180812-10:42:39.282(-7)? (STDERR)     at REPLServer.onLine (repl.js:468:10)
W20180812-10:42:39.282(-7)? (STDERR)     at emitOne (events.js:121:20)
W20180812-10:42:39.282(-7)? (STDERR)     at REPLServer.emit (events.js:211:7)
W20180812-10:42:39.291(-7)? (STDERR)     at REPLServer.Interface._onLine (readline.js:280:10)
W20180812-10:42:39.291(-7)? (STDERR)     at REPLServer.Interface._line (readline.js:629:8)
W20180812-10:42:39.291(-7)? (STDERR)     at REPLServer.Interface._ttyWrite (readline.js:910:14)
W20180812-10:42:39.292(-7)? (STDERR)     at REPLServer.self._ttyWrite (repl.js:537:7)
W20180812-10:42:39.292(-7)? (STDERR)     at PassThrough.onkeypress (readline.js:158:10)
W20180812-10:42:39.292(-7)? (STDERR)     at emitTwo (events.js:126:13)
W20180812-10:42:39.292(-7)? (STDERR)     at PassThrough.emit (events.js:214:7)
W20180812-10:42:39.292(-7)? (STDERR)     at emitKeys (internal/readline.js:420:14)
W20180812-10:42:39.292(-7)? (STDERR)     at emitKeys.next (<anonymous>)
Error: Cannot find module 'package-utils'
    at evalCommandPromise.then (packages/shell-server/shell-server.js:246:21)
    at runBound (domain.js:314:12)
    at bound (domain.js:301:14)
    at defaultEval (repl.js:240:29)
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at repl:1:-61
    at require (packages/modules-runtime.js:244:21)
    at Module.require (packages/modules-runtime.js:227:17)
    at makeMissingError (packages/modules-runtime.js:208:12)
```

**Comment by convexset** [comment]
It's not being bundled up. Include a `require('package-utils')` line in one of your application `.js` files and it will work.

**Comment by convexset** [comment]
Having a simple `server/main.js` with
```js
import { Meteor } from 'meteor/meteor';
import { Log } from 'meteor/convexset:log'

Meteor.startup(() => {
  Log.log(5, 'hi')
});
```
works fine.

**Comment by convexset** [comment]
... or...
```js
import { Meteor } from 'meteor/meteor';
require("package-utils")
Meteor.startup(() => {
  // code to run on server at startup
});
```

**Comment by iwoj** [comment]
Ok. Thanks. I think the problem has to do with my meteor configuration. I'm going to try changing my packages. This is what I have installed 

```
accounts-base                           1.4.2  A user account system
accounts-facebook                       1.3.1  Login service for Facebook accounts
accounts-password                       1.5.1  Password support for accounts
accounts-ui                             1.3.0  Simple templates to add login widgets to an app
alanning:roles                          1.2.16  Authorization package for Meteor
cordova:cordova-plugin-badge            0.8.7
cordova:cordova-plugin-bluetoothle      4.4.4
cordova:cordova-plugin-camera           4.0.3
cordova:cordova-plugin-inappbrowser     1.7.1
cordova:cordova-plugin-meteor-webapp    1.6.0
cordova:cordova-plugin-splashscreen     5.0.2
cordova:cordova-plugin-statusbar        2.4.2
cordova:cordova-universal-links-plugin  https://github.com/PluginCordova/cordova-universal-links-plugin.git#5a1aa1ce564d251c98739a4466aeaf4cf8863be7
cordova:phonegap-plugin-barcodescanner  8.0.0
cordova:phonegap-plugin-push            2.2.3
datariot:ganalytics                     0.2.1  Publish pageviews and events to Google Analytics using the new analytics.js code.
dynamic-import                          0.4.1  Runtime support for Meteor 1.5 dynamic import(...) syntax
ecmascript                              0.11.1  Compiler plugin that supports ES2015+ in all .js files
email                                   1.2.3  Send email messages
facebook-config-ui                      1.0.1  Blaze configuration templates for Facebook OAuth.
http                                    1.4.1  Make HTTP calls to remote servers
insecure                                1.0.7  (For prototyping only) Allow all database writes from the client
iron:router                             1.1.2  Routing specifically designed for Meteor
jquery                                  1.11.11  Manipulate the DOM using CSS selectors
less                                    2.7.12  Leaner CSS language
service-configuration                   1.0.11  Manage the configuration for third-party services
shell-server                            0.3.1  Server-side component of the `meteor shell` command.
spiderable                              1.0.13  Makes the application crawlable to web spiders
standard-app-packages                   1.0.9  Moved to meteor-platform
standard-minifier-css                   1.4.1  Standard css minifier used with Meteor apps by default.
standard-minifier-js                    2.3.4  Standard javascript minifiers used with Meteor apps by default.
twbs:bootstrap                          3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
underscore                              1.0.10  Collection of small helpers: _.map, _.each, ...
vjau:xml2js                             4.4.0   * Simple Meteor Package to import xml2js npm module. Parse XML to JSON, server only. * 
```

**Comment by iwoj** [comment]
I'm getting the same problem with a fresh install following your process.

Steps to reproduce:

```
meteor create logtest
cd logtest
meteor add convexset:log
vi server/main.js # Where I add in import { Log } from 'meteor/convexset:log'
meteor &
```

Results in:

```
=> Exited with code: 1
W20180813-13:04:48.440(-7)? (STDERR) WARNING: npm peer requirements not installed:
W20180813-13:04:48.440(-7)? (STDERR)  - package-utils@^0.2.1 not installed.
W20180813-13:04:48.440(-7)? (STDERR)  - underscore@1.5.2 installed, underscore@^1.8.3 needed
W20180813-13:04:48.441(-7)? (STDERR) 
W20180813-13:04:48.441(-7)? (STDERR) Read more about installing npm peer dependencies:
W20180813-13:04:48.441(-7)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20180813-13:04:48.441(-7)? (STDERR) 
W20180813-13:04:48.463(-7)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.7.0_4.2tkcl7.zvndn++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180813-13:04:48.463(-7)? (STDERR)                                            throw(ex);
W20180813-13:04:48.464(-7)? (STDERR)                                            ^
W20180813-13:04:48.464(-7)? (STDERR) 
W20180813-13:04:48.464(-7)? (STDERR) Error: Cannot find module 'package-utils'
W20180813-13:04:48.464(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180813-13:04:48.465(-7)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180813-13:04:48.465(-7)? (STDERR)     at Object.require (/home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:288:32)
W20180813-13:04:48.465(-7)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
W20180813-13:04:48.465(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180813-13:04:48.465(-7)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180813-13:04:48.465(-7)? (STDERR)     at log.js (packages/convexset:log/log.js:9:26)
W20180813-13:04:48.465(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180813-13:04:48.466(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180813-13:04:48.466(-7)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180813-13:04:48.466(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/packages/convexset_log.js:666:15
W20180813-13:04:48.466(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/packages/convexset_log.js:671:3
W20180813-13:04:48.466(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:411:36
W20180813-13:04:48.466(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20180813-13:04:48.466(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:220:19
W20180813-13:04:48.467(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:471:5
```

So then I:

```
meteor npm install --save package-utils underscore
```

But I get:

```
W20180813-13:05:25.306(-7)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.7.0_4.2tkcl7.zvndn++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180813-13:05:25.306(-7)? (STDERR)                                            throw(ex);
W20180813-13:05:25.306(-7)? (STDERR)                                            ^
W20180813-13:05:25.306(-7)? (STDERR) 
W20180813-13:05:25.307(-7)? (STDERR) TypeError: PackageUtilities.addImmutablePropertyFunction is not a function
W20180813-13:05:25.307(-7)? (STDERR)     at packages/convexset:log/log.js:230:20
W20180813-13:05:25.307(-7)? (STDERR)     at log.js (packages/convexset:log/log.js:103:13)
W20180813-13:05:25.307(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180813-13:05:25.307(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180813-13:05:25.307(-7)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180813-13:05:25.307(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/packages/convexset_log.js:666:15
W20180813-13:05:25.308(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/packages/convexset_log.js:671:3
W20180813-13:05:25.308(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:411:36
W20180813-13:05:25.308(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20180813-13:05:25.308(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:220:19
W20180813-13:05:25.308(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:471:5
W20180813-13:05:25.308(-7)? (STDERR)     at Function.run (/home/ubuntu/logtest/.meteor/local/build/programs/server/profile.js:510:12)
W20180813-13:05:25.308(-7)? (STDERR)     at /home/ubuntu/logtest/.meteor/local/build/programs/server/boot.js:470:11
```

Also:

```
meteor --version
> Meteor 1.7.0.4
meteor npm --version
> 6.3.0
```

**Comment by iwoj** [comment]
I figured out the problem. I have to add the NPM modules before the meteor package.

```
meteor npm install --save package-utils underscore
meteor add convexset:log
```

Very strange.

Now that it's working, it would be nice to be able to do:

```
Log.info("This is a message.");
```

...without setting verbosity. Verbosity for my application is implied by the log/info/warn/error levels.

**Comment by convexset** [comment]
That approach with the verbosity is not the usual intended use. You should create loggers with some configuration (verbosity, tags, whether to store/display the stack trace, whether to record the log arguments) and then use those loggers as a drop in replacement for `console.log`.

**Comment by iwoj** [comment]
That makes sense. Can your system support client side logging that's stored in a collection?

**Comment by convexset** [comment]
It’s there. Shouldn’t be too hard to find in the docs. Multiple collections... you’ll have to add hooks.

**Comment by iwoj** [comment]
On further inspection, it looks like the errors I was having were because I was trying to install your package and NPM dependencies while my app was running. I needed to shut it down, install everything, and then boot it up.
